# Generated by Django 6.0.1 on 2026-02-05 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('focus_sessions_completed', models.PositiveSmallIntegerField(default=0)),
                ('focus_minutes_completed', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_minutes', models.PositiveSmallIntegerField(default=25)),
                ('short_break_minutes', models.PositiveSmallIntegerField(default=5)),
                ('long_break_minutes', models.PositiveSmallIntegerField(default=15)),
                ('long_break_every', models.PositiveSmallIntegerField(default=4)),
                ('daily_goal_sessions', models.PositiveSmallIntegerField(default=8)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('auto_start_break', models.BooleanField(default=False)),
                ('auto_start_focus', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
